/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILaunchpad, ILaunchpadInterface } from "../ILaunchpad";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "buyTokenStatus",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ILaunchpad__factory {
  static readonly abi = _abi;
  static createInterface(): ILaunchpadInterface {
    return new utils.Interface(_abi) as ILaunchpadInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILaunchpad {
    return new Contract(address, _abi, signerOrProvider) as ILaunchpad;
  }
}
